config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'
  
  resources :release_notes
  
  resources :caracteristica_releases
  resources :integracoes, :only => [:new, :create, :destroy]
  resources :observacoes
  resources :tipo_integracoes
  resources :defeitos
  resources :pessoas
  resources :sistemas
  resources :caracteristicas
  
  resources :perfis
  resources :usuarios
  
  #get    'cadastro'  => 'usuarios#cadastro'
  #post   'signup'  => 'usuarios#signup'
  
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get    'signup'  => 'sessions#signup'
  post   'signup'  => 'usuarios#signup'
  get    'reset'   => 'sessions#reset'
  delete 'logout'  => 'sessions#destroy'
  
  
  get 'sessions/new'
  get 'sessions/new' , :as => 'new_session'
  get 'pessoa_sistema/new'
  get 'pessoa_sistema' => 'pessoa_sistema#index'
  get 'pessoa_sistemas' => 'sistema#new'
  post 'pessoa_sistemas' => 'pessoa_sistema#addpessoa'
  
end

app/models/release_note.rb
class ReleaseNote < ActiveRecord::Base
  belongs_to :sistema
  has_many :defeitos
  has_many :observacoes
  has_many :integracoes
  has_many :caracteristica_releases
end

app/controllers/release_notes_controller.rb
class ReleaseNotesController < ApplicationController
  before_action :set_release_note, only: [:show, :edit, :update, :destroy]
  before_action :current_usuario
  before_action :logged_in_usuario
  
  # GET /release_notes
  # GET /release_notes.json
  def index
    @release_notes = ReleaseNote.paginate(page: params[:page], :per_page => 2)
    @release_notes_all = ReleaseNote.all
    
  end

  # GET /release_notes/1
  # GET /release_notes/1.json
  def show
    @sistemas = Sistema.all
    @defeitos = Defeito.where(release_note_id: @release_note.id)
    @observacoes = Observacao.where(release_note_id: @release_note.id)
    @integracoes = Integracao.where(release_note_id: @release_note.id)
    @caracteristica_releases = CaracteristicaRelease.where(release_note_id: @release_note.id)
  end

  # GET /release_notes/new
  def new
    @release_note = ReleaseNote.new
    @sistemas = Sistema.all
    @defeitos = Defeito.where(release_note_id: @release_note.id)
    @observacoes = Observacao.where(release_note_id: @release_note.id)
    @integracoes = Integracao.where(release_note_id: @release_note.id)
    @caracteristica_releases = CaracteristicaRelease.where(release_note_id: @release_note.id)
  end

  # GET /release_notes/1/edit
  def edit
    @sistemas = Sistema.all
    @defeitos = Defeito.where(release_note_id: @release_note.id)
    @observacoes = Observacao.where(release_note_id: @release_note.id)
    @integracoes = Integracao.where(release_note_id: @release_note.id)
    @caracteristica_releases = CaracteristicaRelease.where(release_note_id: @release_note.id)
  end

  # POST /release_notes
  # POST /release_notes.json
  def create

    @release_note = ReleaseNote.new(release_note_params)
    if @release_note.save
      flash[:success] = "Release criada com sucesso !"
      redirect_to edit_release_note_path @release_note, tab:"descricao"
    else
      flash[:danger] = "Falha ao criar Release !"
      render :new
    end
  end

  # PATCH/PUT /release_notes/1
  # PATCH/PUT /release_notes/1.json
  def update
   
      if @release_note.update(release_note_params)
        flash[:success] = "Release atualizado com sucesso !"
        redirect_to release_note_path @release_note, tab:"descricao"
      else
        flash[:success] = "Falha ao atualizar release !"
        render :edit
      end
  end

  # DELETE /release_notes/1
  # DELETE /release_notes/1.json
  def destroy
    @release_note.destroy
    flash[:success] = "Release removido com sucesso !"
    redirect_to release_notes_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_release_note
      @release_note = ReleaseNote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def release_note_params
      params.require(:release_note).permit(:sistema_id, :path_deploy, :contexto, :motivacao, :instrucao_uso, :monitoramento)
    end
end

app/helpers/release_notes_helper.rb
module ReleaseNotesHelper
end

app/views/release_notes/_form.html.erb
<% provide(:title, "#{texto_da_acao} Release Notes" ) %>
<% provide(:template, "admin" ) %>

<%= form_for(@release_note) do |f| %>

  <style>
    .button-add-tab{
      padding: 10px 0px;
    }
  </style>

<div class="card card-default">
  <div class="card-header bordered">
    <div class="header-block">
      <h3 class="title">Release Notes</h3>
    </div>
  </div>
  <div class="card-block">
     <div class="form-group">
        <%= f.label :sistema_id %><br>
        <%= f.collection_select :sistema_id, @sistemas, :id, :nome , {}, class:"form-control" %>
      </div>

        <ul class="nav nav-tabs nav-tabs-bordered">
          <li class="nav-item">
            <a class="<%= if params[:tab] == 'descricao' then 'nav-link active' else 'nav-link' end %>" href="#descricao" role="tab" data-toggle="tab" data-target="#descricao" aria-controls="descricao">Dados Gerais</a>
          </li>
          <% if @release_note.new_record? == false %>
            <li class="nav-item">
              <a class="<%= if params[:tab] == 'caracteristicas' then 'nav-link active' else 'nav-link' end %>" href="#caracteristicas" role="tab" data-toggle="tab" data-target="#caracteristicas" aria-controls="caracteristicas">Características</a>
            </li>
            <li class="nav-item">
              <a class="<%= if params[:tab] == 'integracoes' then 'nav-link active' else 'nav-link' end %>" href="#integracoes" role="tab" data-toggle="tab" data-target="#integracoes" aria-controls="integracoes">Integrações</a>
            </li>
            <li class="nav-item">
              <a class="<%= if params[:tab] == 'defeitos' then 'nav-link active' else 'nav-link' end %>" href="#defeitos" role="tab" data-toggle="tab" data-target="#defeitos" aria-controls="defeitos">Defeitos</a>
            </li>
            <li class="nav-item">
              <a class="<%= if params[:tab] == 'observacoes' then 'nav-link active' else 'nav-link' end %>" href="#observacoes" role="tab" data-toggle="tab" data-target="#observacoes" aria-controls="observacoes">Observações</a>
            </li>
          <% end %>
        </ul>
        <div class="tab-content tabs-bordered">
          <div class="<%= if (params[:tab] == 'descricao' || !params[:tab])then 'tab-pane fade in active'  else 'tab-pane fade' end%>" id="descricao">

            <div class="form-group">
              <%= f.label :path_deploy %><br>
              <%= f.text_field :path_deploy, class:"form-control" %>
            </div>
            <div class="form-group">
              <%= f.label :path_svn %><br>
              <%= f.text_field :path_svn, class:"form-control" %>
            </div>
            <div class="form-group">
              <%= f.label :contexto %><br>
              <%= f.text_field :contexto, class:"form-control" %>
            </div>
            <div class="form-group">
              <%= f.label :motivacao %><br>
              <%= f.text_area :motivacao, class:"form-control" %>
            </div>
            <div class="form-group">
              <%= f.label :instrucao_uso %><br>
              <%= f.text_area :instrucao_uso, class:"form-control" %>
            </div>
            <div class="form-group">
              <%= f.label :monitoramento %><br>
              <%= f.text_field :monitoramento, class:"form-control" %>
            </div>
          </div>
          <% if @release_note.new_record? == false %>
          <div class="<%= if (params[:tab] == 'caracteristicas' || !params[:tab])then 'tab-pane fade in active'  else 'tab-pane fade' end%>" id="caracteristicas">
            
             <div class="card card-default">
              <div class="card-header bordered">
                <div class="header-block">
                  <h3 class="title">Caracteristicas</h3>
                </div>
                <div class="header-block pull-right">
                  <%= link_to new_caracteristica_release_path(:release_id => @release_note.id), class:"btn btn-primary btn-sm active" do %>
                    <span class="fa fa-plus"></span> Novo
                  <% end %>
                </div>
              </div>
              <div class="card-block table-responsive">
                <table class="table table-striped table-bordered table-list">
                <thead>
                    <tr>
                      <th>Caracteristica</th>
                      <th>Descrição</th>
                      <th>Status</th>
                      <th>
                        <div align="center">
                          <span class="fa fa-cog"></span>
                        </div>
                      </th>
                    </tr>
                  </thead>

                  <tbody>
                    <% @caracteristica_releases.each do |cr| %>
                      <tr>
                        <td><%= cr.caracteristica.nome %></td>
                        <td><%= cr.descricao %></td>
                        <td>

                          <%= if cr.status == true then image_tag("circle_green.png", alt:"Sim") else  image_tag("circle_red.png", alt:"Não") end %>
                        </td>
                        
                          
                          <td align="center">
                            <div class="form-inline">
                             <%= link_to cr, method: :delete, class:"btn btn-danger btn-sm" do %>
                                <span class="fa fa-trash"></span>
                              <% end %>
                            </div>
                          
                        </td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
              
            </div>
             
          </div>
          <div class="<%= if (params[:tab] == 'integracoes' || !params[:tab])then 'tab-pane fade in active'  else 'tab-pane fade' end%>" id="integracoes">
             <div class="card card-default">
              <div class="card-header bordered">
                <div class="header-block">
                  <h3 class="title">Integrações</h3>
                </div>
                <div class="header-block pull-right">
                  <%= link_to new_integracao_path(:release_id => @release_note.id), class:"btn btn-primary btn-sm active" do %>
                    <span class="fa fa-plus"></span> Novo
                  <% end %>
                </div>
              </div>
              <div class="card-block table-responsive">
                <table class="table table-striped table-bordered table-list">
                  <thead>
                    <tr>
                      <th>Tipo</th>
                      <th>Descrição</th>
                      <th>
                        <div align="center">
                          <span class="fa fa-cog"></span>
                        </div>
                      </th>
                    </tr>
                  </thead>

                  <tbody>
                    <% @integracoes.each do |integracao| %>
                      <tr>
                        <td><%= integracao.tipo_integracao.nome %></td>
                        <td><%= integracao.descricao %></td>
                        <td align="center">
                            <div class="form-inline">
                             <%= link_to integracao, method: :delete, class:"btn btn-danger btn-sm" do %>
                                <span class="fa fa-trash"></span>
                              <% end %>
                            </div>
                          
                        </td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
              
            </div>
             
          </div>
          <div class="<%= if (params[:tab] == 'defeitos' || !params[:tab])then 'tab-pane fade in active'  else 'tab-pane fade' end%>" id="defeitos">
             
             <div class="card card-default">
              <div class="card-header bordered">
                <div class="header-block">
                  <h3 class="title">Defeitos</h3>
                </div>
                <div class="header-block pull-right">
                  <%= link_to new_defeito_path(:release_id => @release_note.id), class:"btn btn-primary btn-sm active" do %>
                    <span class="fa fa-plus"></span> Novo
                  <% end %>
                </div>
              </div>
              <div class="card-block table-responsive">
                <table class="table table-striped table-bordered table-list">
                  <thead>
                    <tr>
                      <th>Descrição</th>
                      <th>
                        <div align="center">
                          <span class="fa fa-cog"></span>
                        </div>
                      </th>
                    </tr>
                  </thead>

                  <tbody>
                    <% @defeitos.each do |defeito| %>
                      <tr>
                        <td><%= defeito.descricao %></td>
                        <td align="center">
                            <div class="form-inline">
                             <%= link_to defeito, method: :delete, class:"btn btn-danger btn-sm" do %>
                                <span class="fa fa-trash"></span>
                              <% end %>
                            </div>
                          
                        </td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
              
            </div>
             
             
          </div>
          <div class="<%= if (params[:tab] == 'observacoes' || !params[:tab])then 'tab-pane fade in active'  else 'tab-pane fade' end%>" id="observacoes">
             
             <div class="card card-default">
              <div class="card-header bordered">
                <div class="header-block">
                  <h3 class="title">Observações</h3>
                </div>
                <div class="header-block pull-right">
                  <%= link_to new_observacao_path(:release_id => @release_note.id), class:"btn btn-primary btn-sm active" do %>
                    <span class="fa fa-plus"></span> Novo
                  <% end %>
                </div>
              </div>
              <div class="card-block table-responsive">
                <table class="table table-striped table-bordered table-list">
                  <thead>
                    <tr>
                      <th>Descrição</th>
                      <th>
                        <div align="center">
                          <span class="fa fa-cog"></span>
                        </div>
                      </th>
                    </tr>
                  </thead>

                  <tbody>
                    <% @observacoes.each do |observacao| %>
                      <tr>
                        <td><%= observacao.descricao %></td>
                        <td align="center">
                            <div class="form-inline">
                             <%= link_to observacao, method: :delete, class:"btn btn-danger btn-sm" do %>
                                <span class="fa fa-trash"></span>
                              <% end %>
                            </div>
                          
                        </td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
              
            </div>
             
          </div>
          <% end %>
        </div>
      </div>
      <div class="card-footer">
        <div class="row">
          <div class="col">
            <%= f.submit "Salvar", class:"btn btn-primary" %>
            <%= link_to 'Voltar', release_notes_path, class:"btn btn-info" %>
            <% if @release_note.new_record? == false %>
              <%= link_to 'Deletar', @release_note, method: :delete, data: { confirm: 'Tem Certeza?' }, class:"btn btn-danger active" %>
            <% end %>
          </div>
          
        </div>
      </div>
  </div>

<% end %>

app/views/release_notes/index.html.erb
<% provide(:template, "admin" ) %>

<p id="notice"><%= notice %></p>

<div class="card card-default">
  <div class="card-header bordered">
    <div class="header-block">
      <h3 class="title">Release Notes</h3>
    </div>
    <div class="header-block pull-right">
      <%= link_to new_release_note_path(tab:"descricao"), class:"btn btn-primary btn-sm active" do %>
        <span class="fa fa-plus"></span> Novo
      <% end %>
    </div>
  </div>
  <div class="card-block table-responsive">
    <table class="table table-striped table-bordered table-list">
      <thead>
        <tr>
            <tr>
              <th>
                <div align="center">
                  <span class="fa fa-cog"></span>
                </div>
              </th>
              <th>Sistema</th>
              <th>Contexto</th>
            </tr>
        </tr> 
      </thead>
      <tbody>
        <% @release_notes.each do |release_note| %>
          <tr>
            <td align="center">
              <div class="form-inline">
               <%= link_to release_note_path(release_note, tab:"descricao"), class:"btn btn-primary btn-sm" do %>
                  <span class="fa fa-pencil"></span>
                <% end %>
              </div>
            </td>
            <td><%= release_note.sistema.nome %></td>
            <td><%= release_note.contexto %></td>
          </tr>
        <% end %>
              
            </tbody>
    </table>
  </div>
  <div class="card-footer">
    <div class="row">
      <div class="col hidden-xs-down col-md-4">
        <%= page_entries_info @release_notes %>
      </div>
      <div class="col col-xs-12 col-md-8">
        <ul class="pagination  pull-right">
          <li><%= will_paginate @release_notes, :previous_label => image_tag('previous.png', :alt => 'Anterior', :class => 'glyphicon glyphicon-chevron-left') ,:next_label => image_tag('next.png', :alt => 'Próximo', :class => 'btn_img') , :separator => ' | ', :params => params %> </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/release_notes/show.html.erb
<% provide(:title, "Visualizar Release Notes" ) %>
<% provide(:template, "admin" ) %>

<p id="notice"><%= notice %></p>


<%= form_for(@release_note) do |f| %>
  
  <style>
    .button-add-tab{
      padding: 10px 0px;
    }
    .panel{
     margin-top: 10px;
    }
  </style>

<div class="card card-default">
  <div class="card-header bordered">
    <div class="header-block">
      <h3 class="title">Release Notes</h3>
    </div>
  </div>
  <div class="card-block">
     <p>
          <strong>Sistema:</strong>
          <output type="text" class="form-control" id="nome" ><%= @release_note.sistema.nome %></output>
        </p>
        
        <ul class="nav nav-tabs nav-tabs-bordered">
          <li class="<%= if params[:tab] == 'descricao' then 'nav-item' else 'nav-item' end %>">
            <a class="nav-link active" href="#descricao" role="tab" data-toggle="tab" data-target="#descricao" aria-controls="descricao">Dados Gerais</a>
          </li>
          <li class="<%= if params[:tab] == 'caracteristicas' then 'nav-item' else 'nav-item' end %>">
            <a class="nav-link" href="#caracteristicas" role="tab" data-toggle="tab" data-target="#caracteristicas" aria-controls="caracteristicas">Características</a>
          </li>
          <li class="<%= if params[:tab] == 'integracoes' then 'nav-item' else 'nav-item' end %>">
            <a class="nav-link" href="#integracoes" role="tab" data-toggle="tab" data-target="#integracoes" aria-controls="integracoes">Integrações</a>
          </li>
          <li class="<%= if params[:tab] == 'defeitos' then 'nav-item' else 'nav-item' end %>">
            <a class="nav-link" href="#defeitos" role="tab" data-toggle="tab" data-target="#defeitos" aria-controls="defeitos">Defeitos</a>
          </li>
          <li class="<%= if params[:tab] == 'observacoes' then 'nav-item' else 'nav-item' end %>">
            <a class="nav-link" href="#observacoes" role="tab" data-toggle="tab" data-target="#observacoes" aria-controls="observacoes">Observações</a>
          </li>
          
        </ul>
        <div class="tab-content tabs-bordered">
            <div role="tabpanel" class="<%= if (params[:tab] == 'descricao' || !params[:tab])then 'tab-pane fade in active'  else 'tab-pane fade' end%>" id="descricao">
              
              <p>
                <strong>Path deploy:</strong>
                <output type="text" class="form-control" id="nome" ><%= @release_note.path_deploy %></output>
              </p>
              
              <p>
                <strong>Path svn:</strong>
                <output type="text" class="form-control" id="nome" ><%= @release_note.path_svn %></output>
              </p>
              
              <p>
                <strong>Contexto:</strong>
                <output type="text" class="form-control" id="nome" ><%= @release_note.contexto %></output>
              </p>
              
              <p>
                <strong>Motivacao:</strong>
                <output type="text" class="form-control" id="nome" ><%= @release_note.motivacao %></output>
              </p>
              
              <p>
                <strong>Instrucao uso:</strong>
                <output type="text-area" class="form-control" id="nome" ><%= @release_note.instrucao_uso %></output>
              </p>
              
              <p>
                <strong>Monitoramento:</strong>
                <output type="text" class="form-control" id="nome" ><%= @release_note.monitoramento %></output>
              </p>
            </div>
            <div role="tabpanel" class="<%= if (params[:tab] == 'caracteristicas' || !params[:tab])then 'tab-pane fade in active'  else 'tab-pane fade' end%>" id="caracteristicas">
              
               <div class="panel panel-default">
                <div class="panel-heading">
                  <h3 class="panel-title">Lista de Caracteristicas</h3>
                </div> 
                <div class="panel-body table-responsive">
                  <table class="table table-hover">
                    <thead>
                      <tr>
                        <th>Caracteristica</th>
                        <th>Descrição</th>
                        <th>Status</th>
                        
                      </tr>
                    </thead>
                  
                    <tbody>
                      <% @caracteristica_releases.each do |cr| %>
                        <tr>
                          <td><%= cr.caracteristica.nome %></td>
                          <td><%= cr.descricao %></td>
                          <td>
                            
                            <%= if cr.status == true then image_tag("circle_green.png", alt:"Sim") else  image_tag("circle_red.png", alt:"Não") end %>
                          </td>
                          
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
            <div role="tabpanel" class="<%= if (params[:tab] == 'integracoes' || !params[:tab])then 'tab-pane fade in active'  else 'tab-pane fade' end%>" id="integracoes">
              
               <div class="panel panel-default">
                <div class="panel-heading">
                  <h3 class="panel-title">Lista de Integrações</h3>
                </div>
                <div class="panel-body table-responsive">
                  <table class="table table-hover">
                    <thead>
                      <tr>
                        <th>Tipo</th>
                        <th>Descrição</th>
                        
                      </tr>
                    </thead>
                  
                    <tbody>
                      <% @integracoes.each do |integracao| %>
                        <tr>
                          <td><%= integracao.tipo_integracao.nome %></td>
                          <td><%= integracao.descricao %></td>
                          
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
            <div role="tabpanel" class="<%= if (params[:tab] == 'defeitos' || !params[:tab])then 'tab-pane fade in active'  else 'tab-pane fade' end%>" id="defeitos">
              
               <div class="panel panel-default">
                <div class="panel-heading">
                  <h3 class="panel-title">Lista de Defeitos</h3>
                </div>
                <div class="panel-body table-responsive">
                  <table class="table table-hover">
                    <thead>
                      <tr>
                        <th>Descrição</th>
                        
                      </tr>
                    </thead>
                  
                    <tbody>
                      <% @defeitos.each do |defeito| %>
                        <tr>
                          <td><%= defeito.descricao %></td>
                          
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
            <div role="tabpanel" class="<%= if (params[:tab] == 'observacoes' || !params[:tab])then 'tab-pane fade in active'  else 'tab-pane fade' end%>" id="observacoes">
              
               <div class="panel panel-default">
                <div class="panel-heading">
                  <h3 class="panel-title">Lista de Observações</h3>
                </div>
                <div class="panel-body table-responsive">
                  <table class="table table-hover">
                    <thead>
                      <tr>
                        <th>Descrição</th>
                        
                      </tr>
                    </thead>
                  
                    <tbody>
                      <% @observacoes.each do |observacao| %>
                        <tr>
                          <td><%= observacao.descricao %></td>
                          
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
        </div>
          
      
    </div>


  <div class="card-footer">
    <div class="row">
      <div class="col">
        <%= link_to 'Editar', edit_release_note_path(@release_note, tab:"descricao"), class:"btn btn-warning active" %>
        <%= link_to 'Voltar', release_notes_path, class:"btn btn-info" %>
      </div>
      
    </div>
  </div>
</div>
<% end %>