config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'
  
  resources :release_notes
  
  resources :caracteristica_releases
  resources :integracoes, :only => [:new, :create, :destroy]
  resources :observacoes
  resources :tipo_integracoes
  resources :defeitos
  resources :pessoas
  resources :sistemas
  resources :caracteristicas
  
  resources :perfis
  resources :usuarios
  
  #get    'cadastro'  => 'usuarios#cadastro'
  #post   'signup'  => 'usuarios#signup'
  
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get    'signup'  => 'sessions#signup'
  post   'signup'  => 'usuarios#signup'
  get    'reset'   => 'sessions#reset'
  delete 'logout'  => 'sessions#destroy'
  
  
  get 'sessions/new'
  get 'sessions/new' , :as => 'new_session'
  get 'pessoa_sistema/new'
  get 'pessoa_sistema' => 'pessoa_sistema#index'
  get 'pessoa_sistemas' => 'sistema#new'
  post 'pessoa_sistemas' => 'pessoa_sistema#addpessoa'
  
end

app/models/caracteristica.rb
class Caracteristica < ActiveRecord::Base
    has_many :caracteristica_releases
    has_many :release_note, :through => :caracteristica_releases
end

app/models/defeito.rb
class Defeito < ActiveRecord::Base
  belongs_to :release_note
end

app/models/integracao.rb
class Integracao < ActiveRecord::Base
  belongs_to :tipo_integracao
  belongs_to :release_note
end

app/models/observacao.rb
class Observacao < ActiveRecord::Base
  belongs_to :release_note
end

app/models/perfil.rb
class Perfil < ActiveRecord::Base
end

app/models/pessoa.rb
class Pessoa < ActiveRecord::Base
    has_many :pessoa_sistemas
    has_many :sistemas, :through => :pessoa_sistemas
end

app/models/pessoa_sistema.rb
class PessoaSistema < ActiveRecord::Base
  belongs_to :sistema
  belongs_to :pessoa
end

app/models/release_note.rb
class ReleaseNote < ActiveRecord::Base
  belongs_to :sistema
  has_many :defeitos
  has_many :observacoes
  has_many :integracoes
  has_many :caracteristica_releases
end

app/models/sistema.rb
class Sistema < ActiveRecord::Base
    has_one  :release_notes
    has_many :pessoa_sistemas
    has_many :pessoas, :through => :pessoa_sistemas
end

app/models/tipo_integracao.rb
class TipoIntegracao < ActiveRecord::Base
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  belongs_to :perfil
  
  before_save { self.email = email.downcase }
  validates :nome, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  
  # Forgets a user.
  def forget
      update_attribute(:relembreme_digest, nil)
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/pessoas_controller.rb
class PessoasController < ApplicationController
  before_action :set_pessoa, only: [:show, :edit, :update, :destroy]
  before_action :current_usuario
  before_action :logged_in_usuario

  # GET /pessoas
  # GET /pessoas.json
  def index
    @pessoas = Pessoa.paginate(page: params[:page], :per_page => 10)
  end

  # GET /pessoas/1
  # GET /pessoas/1.json
  def show
  end

  # GET /pessoas/new
  def new
    @pessoa = Pessoa.new
  end

  # GET /pessoas/1/edit
  def edit
  end

  # POST /pessoas
  # POST /pessoas.json
  def create
    @pessoa = Pessoa.new(pessoa_params)
      if @pessoa.save
          flash[:success] = "Pessoa criada com sucesso !"
          redirect_to pessoas_path
      else

      end
  end

  # PATCH/PUT /pessoas/1
  # PATCH/PUT /pessoas/1.json
  def update
    #respond_to do |format|
      if @pessoa.update(pessoa_params)
        #format.html { redirect_to @pessoa, notice: 'Pessoa was successfully updated.' }
        #format.json { render :show, status: :ok, location: @pessoa }
         flash[:success] = "Pessoa Atualizada com Sucesso !"
        redirect_to pessoas_path
      else
        flash[:danger] = "Erro ao Atualizar Pessoa !"
        render :new
     #   format.html { render :edit }
    #    format.json { render json: @pessoa.errors, status: :unprocessable_entity }

      end
   # end
  end

  # DELETE /pessoas/1
  # DELETE /pessoas/1.json
  def destroy
    @pessoa.destroy
    respond_to do |format|
      format.html { redirect_to pessoas_url, notice: 'Pessoa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pessoa
      @pessoa = Pessoa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pessoa_params
      params.require(:pessoa).permit(:nome, :email, :matricula)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Release Notes"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
    
end

app/helpers/defeitos_helper.rb
module DefeitosHelper
end

app/helpers/integracao_helper.rb
module IntegracaoHelper
end

app/helpers/observacoes_helper.rb
module ObservacoesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/perfis_helper.rb
module PerfisHelper
end

app/helpers/pessoas_helper.rb
module PessoasHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
    # Logs in the given usuario.
    def log_in(usuario)
        session[:usuario_id] = usuario.id
    end
    
    # Logs out the current usuario.
    def log_out
        forget(current_usuario)
        session.delete(:usuario_id)
        @current_usuario = nil
    end

    # Remembers a usuario in a persistent session.
    def remember(usuario)
        usuario.remember
        cookies.permanent.signed[:usuario_id] = usuario.id
        cookies.permanent[:remember_token] = usuario.remember_token
        
        #cookies[:remember_token] = { value:   remember_token,
        #                             expires: 20.years.from_now.utc }
    end
    
    # Forgets a persistent session.
    def forget(usuario)
        usuario.forget
        cookies.delete(:usuario_id)
        cookies.delete(:remember_token)
    end
    
    # Redirects to stored location (or to the default).
    def redirect_back_or(default)
        redirect_to(session[:forwarding_url] || default)
        session.delete(:forwarding_url)
    end
    
    # Returns true if the usuario is logged in, false otherwise.
    def logged_in?
        !current_usuario.nil?
    end
    
    # Returns the current logged-in usuario (if any).
    def current_usuario
        if (usuario_id = session[:usuario_id])
            @current_usuario ||= Usuario.find_by(id: usuario_id)
        elsif (usuario_id = cookies.signed[:usuario_id])
            usuario = Usuario.find_by(id: usuario_id)
            #if usuario && usuario.authenticated?(cookies[:remember_token])
            if usuario && usuario.authenticated?(:remember, cookies[:remember_token])
                log_in usuario
                @current_usuario = usuario
            end
        end
    end
    
    # Returns true if the given usuario is the current usuario.
    def current_usuario?(usuario)
        usuario == current_usuario
    end
    
    # Confirms a logged-in usuario.
    def logged_in_usuario
      unless logged_in?
      store_location
        flash[:warning] = "Efetue Login."
        redirect_to login_url
      end
    end
    
    # Stores the URL trying to be accessed.
    def store_location
        session[:forwarding_url] = request.url if request.get?
    end
    
end

app/helpers/sistemas_helper.rb
module SistemasHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
    # Returns the Gravatar for the given usuario.
    def gravatar_for(usuario)
        if usuario.email.nil? == false
            gravatar_id = Digest::MD5::hexdigest(usuario.email.downcase)
            gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
            image_tag(gravatar_url, alt: usuario.nome, class: "gravatar")
        end 
    end
end

app/views/pessoas/_form.html.erb
<% provide(:title, "#{texto_da_acao} Pessoa" ) %>
<% provide(:template, "admin" ) %>

<%= form_for(@pessoa) do |f| %>


<div class="card card-default">
  <div class="card-header bordered">
    <div class="header-block">
      <h3 class="title">Pessoa</h3>
    </div>
  </div>
  <div class="card-block">
  <div class="form-group">
    <%= f.label :nome %><br>
    <%= f.text_field :nome, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :email %><br>
    <%= f.text_field :email, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :matricula %><br>
    <%= f.text_field :matricula, class:"form-control" %>
  </div>


</div>



  <div class="card-footer">
    <div class="row">
      <div class="col">
         <%= f.submit texto_da_acao, class:"btn btn-primary" %>
          <%= link_to 'Voltar', pessoas_path, class:"btn btn-info active" %>
          <% if @pessoa.new_record? == false %>
            <%= link_to 'Deletar', @pessoa, method: :delete, data: { confirm: 'Tem Certeza?' }, class:"btn btn-danger active" %>
          <% end %>
      </div>
      
    </div>
  </div>
</div>

<% end %>

app/views/pessoas/index.html.erb
<% provide(:template, "admin" ) %>

<p id="notice"><%= notice %></p>


<div class="card card-default">
  <div class="card-header bordered">
    <div class="header-block">
      <h3 class="title">Pessoas</h3>
    </div>
    <div class="header-block pull-right">
      <%= link_to new_pessoa_path, class:"btn btn-primary btn-sm active" do %>
        <span class="fa fa-plus"></span> Novo
      <% end %>
    </div>
  </div>
  <div class="card-block table-responsive">

                <table class="table table-striped table-bordered table-list">
  <thead>
    <tr>
      <th>
            <div align="center">
              <span class="fa fa-cog"></span>
            </div>
          </th>
      <th>Nome</th>
      <th>Email</th>
      <th>Matricula</th>
    </tr>
  </thead>

  <tbody>
    <% @pessoas.each do |pessoa| %>
      <tr>
        
        <td align="center">
              <div class="form-inline">
               <%= link_to pessoa, class:"btn btn-primary btn-sm" do %>
                  <span class="fa fa-pencil"></span>
                <% end %>
              </div>
            </td>
        <td><%= pessoa.nome %></td>
        <td><%= pessoa.email %></td>
        <td><%= pessoa.matricula %></td>

      </tr>
    <% end %>
  </tbody>
</table>
  </div>
  <div class="card-footer">
    <div class="row">
      <div class="col hidden-xs-down col-md-4">
        <%= page_entries_info @pessoas %>
      </div>
      <div class="col col-xs-12 col-md-8">
        <ul class="pagination  pull-right">
          <li><%= will_paginate @pessoas, :previous_label => image_tag('previous.png', :alt => 'Anterior', :class => 'glyphicon glyphicon-chevron-left') ,:next_label => image_tag('next.png', :alt => 'Próximo', :class => 'btn_img') , :separator => ' | ', :params => params %> </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/pessoas/new.html.erb
<%= render partial: 'form', locals: {texto_da_acao: 'Criar'} %>

app/views/pessoas/show.html.erb
<% provide(:template, "admin" ) %>

<p id="notice"><%= notice %></p>

<div class="card card-default">
  <div class="card-header bordered">
    <div class="header-block">
      <h3 class="title">Pessoa</h3>
    </div>
  </div>
  <div class="card-block">

                  <div class="form-group">
                    <label for="nome">Nome</label>
                    <output type="text" class="form-control" id="nome" ><%= @pessoa.nome %></output>
                  </div>

                  <div class="form-group">
                    <label for="email">E-mail</label>
                    <output type="email" class="form-control" id="email" ><%= @pessoa.email %></output>
                  </div>

                  <div class="form-group">
                    <label for="matricula">Matricula</label>
                    <output type="text" class="form-control" id="matricula" ><%= @pessoa.matricula %></output>
                  </div>
<div class="card-footer">
    <div class="row">
      <div class="col">
         <%= link_to 'Editar', edit_pessoa_path(@pessoa), class:"btn btn-warning active" %>
         <%= link_to 'Voltar', pessoas_path, class:"btn btn-info active" %>
      </div>
      
    </div>
  </div>
</div>