config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'
  
  resources :release_notes
  
  resources :caracteristica_releases
  resources :integracoes, :only => [:new, :create, :destroy]
  resources :observacoes
  resources :tipo_integracoes
  resources :defeitos
  resources :pessoas
  resources :sistemas
  resources :caracteristicas
  
  resources :perfis
  resources :usuarios
  
  #get    'cadastro'  => 'usuarios#cadastro'
  #post   'signup'  => 'usuarios#signup'
  
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get    'signup'  => 'sessions#signup'
  post   'signup'  => 'usuarios#signup'
  get    'reset'   => 'sessions#reset'
  delete 'logout'  => 'sessions#destroy'
  
  
  get 'sessions/new'
  get 'sessions/new' , :as => 'new_session'
  get 'pessoa_sistema/new'
  get 'pessoa_sistema' => 'pessoa_sistema#index'
  get 'pessoa_sistemas' => 'sistema#new'
  post 'pessoa_sistemas' => 'pessoa_sistema#addpessoa'
  
end

app/models/caracteristica.rb
class Caracteristica < ActiveRecord::Base
    has_many :caracteristica_releases
    has_many :release_note, :through => :caracteristica_releases
end

app/models/defeito.rb
class Defeito < ActiveRecord::Base
  belongs_to :release_note
end

app/models/integracao.rb
class Integracao < ActiveRecord::Base
  belongs_to :tipo_integracao
  belongs_to :release_note
end

app/models/observacao.rb
class Observacao < ActiveRecord::Base
  belongs_to :release_note
end

app/models/perfil.rb
class Perfil < ActiveRecord::Base
end

app/models/pessoa.rb
class Pessoa < ActiveRecord::Base
    has_many :pessoa_sistemas
    has_many :sistemas, :through => :pessoa_sistemas
end

app/models/pessoa_sistema.rb
class PessoaSistema < ActiveRecord::Base
  belongs_to :sistema
  belongs_to :pessoa
end

app/models/release_note.rb
class ReleaseNote < ActiveRecord::Base
  belongs_to :sistema
  has_many :defeitos
  has_many :observacoes
  has_many :integracoes
  has_many :caracteristica_releases
end

app/models/sistema.rb
class Sistema < ActiveRecord::Base
    has_one  :release_notes
    has_many :pessoa_sistemas
    has_many :pessoas, :through => :pessoa_sistemas
end

app/models/tipo_integracao.rb
class TipoIntegracao < ActiveRecord::Base
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  belongs_to :perfil
  
  before_save { self.email = email.downcase }
  validates :nome, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  
  # Forgets a user.
  def forget
      update_attribute(:relembreme_digest, nil)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
    
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Release Notes"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
    
end

app/helpers/defeitos_helper.rb
module DefeitosHelper
end

app/helpers/integracao_helper.rb
module IntegracaoHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/perfis_helper.rb
module PerfisHelper
end

app/helpers/pessoas_helper.rb
module PessoasHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
    # Logs in the given usuario.
    def log_in(usuario)
        session[:usuario_id] = usuario.id
    end
    
    # Logs out the current usuario.
    def log_out
        forget(current_usuario)
        session.delete(:usuario_id)
        @current_usuario = nil
    end

    # Remembers a usuario in a persistent session.
    def remember(usuario)
        usuario.remember
        cookies.permanent.signed[:usuario_id] = usuario.id
        cookies.permanent[:remember_token] = usuario.remember_token
        
        #cookies[:remember_token] = { value:   remember_token,
        #                             expires: 20.years.from_now.utc }
    end
    
    # Forgets a persistent session.
    def forget(usuario)
        usuario.forget
        cookies.delete(:usuario_id)
        cookies.delete(:remember_token)
    end
    
    # Redirects to stored location (or to the default).
    def redirect_back_or(default)
        redirect_to(session[:forwarding_url] || default)
        session.delete(:forwarding_url)
    end
    
    # Returns true if the usuario is logged in, false otherwise.
    def logged_in?
        !current_usuario.nil?
    end
    
    # Returns the current logged-in usuario (if any).
    def current_usuario
        if (usuario_id = session[:usuario_id])
            @current_usuario ||= Usuario.find_by(id: usuario_id)
        elsif (usuario_id = cookies.signed[:usuario_id])
            usuario = Usuario.find_by(id: usuario_id)
            #if usuario && usuario.authenticated?(cookies[:remember_token])
            if usuario && usuario.authenticated?(:remember, cookies[:remember_token])
                log_in usuario
                @current_usuario = usuario
            end
        end
    end
    
    # Returns true if the given usuario is the current usuario.
    def current_usuario?(usuario)
        usuario == current_usuario
    end
    
    # Confirms a logged-in usuario.
    def logged_in_usuario
      unless logged_in?
      store_location
        flash[:warning] = "Efetue Login."
        redirect_to login_url
      end
    end
    
    # Stores the URL trying to be accessed.
    def store_location
        session[:forwarding_url] = request.url if request.get?
    end
    
end

app/helpers/sistemas_helper.rb
module SistemasHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
    # Returns the Gravatar for the given usuario.
    def gravatar_for(usuario)
        if usuario.email.nil? == false
            gravatar_id = Digest::MD5::hexdigest(usuario.email.downcase)
            gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
            image_tag(gravatar_url, alt: usuario.nome, class: "gravatar")
        end 
    end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    
    <div class="footer-block buttons">
        <%= image_tag("favicon.ico", alt:"Governo_Ceara") %>
        
    </div>
    <div class="footer-block author">
        <ul>
            <li>  © 2016 - Governo do Estado do Ceará. </li>
            <li> Todos os direitos reservados. </li>
        </ul>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header class="header">
    <div class="header-block header-block-collapse hidden-lg-up"> <button class="collapse-btn" id="sidebar-collapse-btn">
<i class="fa fa-bars"></i>
</button> </div>
    <div class="header-block header-block-search hidden-sm-down">
        <!--form role="search">
            <div class="input-container"> <i class="fa fa-search"></i> <input type="search" placeholder="Search">
                <div class="underline"></div>
            </div>
        </form-->
    </div>
    <div class="header-block header-block-buttons">
        <!--a href="https://github.com/modularcode/modular-admin-html" class="btn btn-oval btn-sm rounded-s header-btn"> <i class="fa fa-github-alt"></i> View on GitHub </a>
        <a href="https://github.com/modularcode/modular-admin-html/releases/download/v1.0.1/modular-admin-html-1.0.1.zip" class="btn btn-oval btn-sm rounded-s header-btn"> <i class="fa fa-cloud-download"></i> Download .zip </a-->
    </div>
    <div class="header-block header-block-nav">
        <ul class="nav-profile">
            <!--li class="notifications new">
                <a href="" data-toggle="dropdown"> <i class="fa fa-bell-o"></i> 
                    <sup>
                <span class="counter">8</span>
              </sup> 
          </a>
                <div class="dropdown-menu notifications-dropdown-menu">
                    <ul class="notifications-container">
                        <li>
                            <a href="" class="notification-item">
                                <div class="img-col">
                                    <div class="img" style="background-image: url('assets/faces/3.jpg')"></div>
                                </div>
                                <div class="body-col">
                                    <p> <span class="accent">Zack Alien</span> pushed new commit: <span class="accent">Fix page load performance issue</span>. </p>
                                </div>
                            </a>
                        </li>
                        <li>
                            <a href="" class="notification-item">
                                <div class="img-col">
                                    <div class="img" style="background-image: url('assets/faces/5.jpg')"></div>
                                </div>
                                <div class="body-col">
                                    <p> <span class="accent">Amaya Hatsumi</span> started new task: <span class="accent">Dashboard UI design.</span>. </p>
                                </div>
                            </a>
                        </li>
                        <li>
                            <a href="" class="notification-item">
                                <div class="img-col">
                                    <div class="img" style="background-image: url('assets/faces/8.jpg')"></div>
                                </div>
                                <div class="body-col">
                                    <p> <span class="accent">Andy Nouman</span> deployed new version of <span class="accent">NodeJS REST Api V3</span> </p>
                                </div>
                            </a>
                        </li>
                    </ul>
                    <footer>
                        <ul>
                            <li> <a href="">
      View All
    </a> </li>
                        </ul>
                    </footer>
                </div>
            </li-->
            <li class="profile dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                     <%= gravatar_for @current_usuario%>
                    
                    <span class="name">
                        <%= @current_usuario.nome %>
                    </span> 
                    </a>
                <div class="dropdown-menu profile-dropdown-menu" aria-labelledby="dropdownMenu1">
                    <a class="dropdown-item" href="#"> <i class="fa fa-user icon"></i> Profile </a>
                    <a class="dropdown-item" href="#"> <i class="fa fa-bell icon"></i> Notifications </a>
                    <a class="dropdown-item" href="#"> <i class="fa fa-gear icon"></i> Settings </a>
                    <div class="dropdown-divider"></div>
                    <%= link_to logout_path, method: "delete", class:"dropdown-item" do %>
                        <i class="fa fa-power-off icon"></i> Logout
                    <% end %>
                </div>
            </li>
        </ul>
    </div>
</header>

app/views/layouts/_header_bk.html.1.erb
<header>
    <nav class="navbar navbar-fixed-top navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <a href="#" class="navbar-brand">Release Notes</a>
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#home">Home</a></li>
            <li><%= link_to "Releases", release_notes_path %></li>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">Gestão<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Sistemas", sistemas_path %></li>
                <li><%= link_to "Pessoas", pessoas_path %></li>
                <li><%= link_to "Tipos de Integração", tipo_integracoes_path %></li>
                <li><%= link_to "Caracteristicas", caracteristicas_path %></li>
              </ul>
            </li>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#">Minha Conta <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Meu Perfil</a></li>
                <li><a href="#">Alterar Senha</a></li>
                <li><a href="#">Loggout</a></li>
              </ul>
            </li>
          </ul>
          <form class="navbar-form navbar-right">
            <div class="form-group">
                <input type="text" class="form-control" placeholder="O que procura?"/>
            </div>
            <input type="submit" value="Buscar" class="btn btn-default" />
          </form>
        </div>
      </div>
    </nav>
</header>

app/views/layouts/_menu_lateral.html.erb
<aside class="sidebar">
    <div class="sidebar-container">
        <div class="sidebar-header">
            <div class="brand">
                <div class="logo">
                    <span class="l l1"></span> <span class="l l2"></span> <span class="l l3"></span> <span class="l l4"></span> <span class="l l5"></span> 
                    <!--%= image_tag("brasao.png", alt:"Governo_Ceara") %-->
                </div> Release Notes 
            </div>
        </div>
        <nav class="menu">
            <ul class="nav metismenu" id="sidebar-menu">
                <li class="active">
                    <%= link_to release_notes_path do %>
                        <i class="fa fa-home"></i> Home
                    <% end %>
                </li>
                <li>
                    <%= link_to release_notes_path do %>
                      <i class="fa fa-pencil-square-o"></i> Releases
                    <% end %>
                </li>
                <li>
                    <a href=""> <i class="fa fa-desktop"></i> Gestão <i class="fa arrow"></i> </a>
                    <ul>
                        <li>
                            <%= link_to sistemas_path do %>
                                Sistemas
                            <% end %>
                        </li>
                         <li>
                            <%= link_to pessoas_path do %>
                                Pessoas
                            <% end %>
                        </li>
                         <li>
                            <%= link_to tipo_integracoes_path do %>
                                Tp. Integração
                            <% end %>
                        </li>
                         <li>
                            <%= link_to caracteristicas_path do %>
                                Caracteristicas
                            <% end %>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href=""> <i class="fa fa-users"></i> Acesso <i class="fa arrow"></i> </a>
                    <ul>
                        <li>
                            <%= link_to usuarios_path do %>
                                Usuários
                            <% end %>
                        </li>
                         <li>
                            <%= link_to perfis_path do %>
                                Perfis
                            <% end %>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="https://github.com/modularcode/modular-admin-html"> <i class="fa fa-github-alt"></i> Sobre </a>
                </li>
            </ul>
        </nav>
    </div>
    <footer class="sidebar-footer">
        <ul class="nav metismenu" id="customize-menu">
            <li>
                <ul>
                    <li class="customize">
                        <div class="customize-item">
                            <div class="row customize-header">
                                <div class="col-xs-4"> </div>
                                <div class="col-xs-4"> <label class="title">fixed</label> </div>
                                <div class="col-xs-4"> <label class="title">static</label> </div>
                            </div>
                            <div class="row hidden-md-down">
                                <div class="col-xs-4"> <label class="title">Sidebar:</label> </div>
                                <div class="col-xs-4"> <label>
	                        <input class="radio" type="radio" name="sidebarPosition" value="sidebar-fixed" >
	                        <span></span>
	                    </label> </div>
                                <div class="col-xs-4"> <label>
	                        <input class="radio" type="radio" name="sidebarPosition" value="">
	                        <span></span>
	                    </label> </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-4"> <label class="title">Header:</label> </div>
                                <div class="col-xs-4"> <label>
	                        <input class="radio" type="radio" name="headerPosition" value="header-fixed">
	                        <span></span>
	                    </label> </div>
                                <div class="col-xs-4"> <label>
	                        <input class="radio" type="radio" name="headerPosition" value="">
	                        <span></span>
	                    </label> </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-4"> <label class="title">Footer:</label> </div>
                                <div class="col-xs-4"> <label>
	                        <input class="radio" type="radio" name="footerPosition" value="footer-fixed">
	                        <span></span>
	                    </label> </div>
                                <div class="col-xs-4"> <label>
	                        <input class="radio" type="radio" name="footerPosition" value="">
	                        <span></span>
	                    </label> </div>
                            </div>
                        </div>
                        <div class="customize-item">
                            <ul class="customize-colors">
                                <li> <span class="color-item color-red" data-theme="red"></span> </li>
                                <li> <span class="color-item color-orange" data-theme="orange"></span> </li>
                                <li> <span class="color-item color-green" data-theme="green"></span> </li>
                                <li> <span class="color-item color-seagreen" data-theme="seagreen"></span> </li>
                                <li> <span class="color-item color-blue active" data-theme=""></span> </li>
                                <li> <span class="color-item color-purple" data-theme="purple"></span> </li>
                            </ul>
                        </div>
                    </li>
                </ul>
                <a href=""> <i class="fa fa-cog"></i> Configurações </a>
            </li>
        </ul>
    </footer>
</aside>

<div class="sidebar-overlay" id="sidebar-overlay">
                  
</div>

app/views/layouts/_modais.html.erb
<div class="modal fade" id="modal-media">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header"> <button type="button" class="close" data-dismiss="modal" aria-label="Close">
		<span aria-hidden="true">&times;</span>
		<span class="sr-only">Close</span>
	</button>
                <h4 class="modal-title">Media Library</h4> </div>
            <div class="modal-body modal-tab-container">
                <ul class="nav nav-tabs modal-tabs" role="tablist">
                    <li class="nav-item"> <a class="nav-link" href="#gallery" data-toggle="tab" role="tab">Gallery</a> </li>
                    <li class="nav-item"> <a class="nav-link active" href="#upload" data-toggle="tab" role="tab">Upload</a> </li>
                </ul>
                <div class="tab-content modal-tab-content">
                    <div class="tab-pane fade" id="gallery" role="tabpanel">
                        <div class="images-container">
                            <div class="row"> </div>
                        </div>
                    </div>
                    <div class="tab-pane fade active in" id="upload" role="tabpanel">
                        <div class="upload-container">
                            <div id="dropzone">
                                <form action="/" method="POST" enctype="multipart/form-data" class="dropzone needsclick dz-clickable" id="demo-upload">
                                    <div class="dz-message-block">
                                        <div class="dz-message needsclick"> Drop files here or click to upload. </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer"> <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button> <button type="button" class="btn btn-primary">Insert Selected</button> </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

<!-- /.modal -->
<div class="modal fade" id="confirm-modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header"> <button type="button" class="close" data-dismiss="modal" aria-label="Close">
		<span aria-hidden="true">&times;</span>
	</button>
                <h4 class="modal-title"><i class="fa fa-warning"></i> Alert</h4> </div>
            <div class="modal-body">
                <p>Are you sure want to do this?</p>
            </div>
            <div class="modal-footer"> <button type="button" class="btn btn-primary" data-dismiss="modal">Yes</button> <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button> </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

app/views/layouts/application.html.erb
<!doctype html>
<html class="no-js" lang="en">
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta charset="UTF-8" >
    <meta name="viewport" content="width=device-width" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="main-wrapper">
      <div class="app" id="app">
        <% if yield(:template) == "admin" then %>
          <%= render 'layouts/header' %>
          <%= render 'layouts/menu_lateral' %>
          <div class="content dashboard-page">
            <% flash.each do |message_type, message| %>
              <div class="alert alert-<%= message_type %>"><%= message %></div>
            <% end %>
            <%= yield %>
          </div>
          <%= render 'layouts/footer' %>
          <%= render 'layouts/modais' %>
        <% else %>
          <%= yield %>
        <% end %>
      </div>
    </div>
    <!-- Reference block for JS -->
    <div class="ref" id="ref">
      <div class="color-primary"></div>
        <div class="chart">
          <div class="color-primary"></div>
          <div class="color-secondary"></div>
        </div>
    </div>
  </body>
</html>